# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fume}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sunteya"]
  s.date = %q{2009-12-21}
  s.email = %q{Sunteya@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION.yml",
     "fume.gemspec",
     "generators/fume/capify/capify_gen.rb",
     "generators/fume/capify/templates/Capfile",
     "generators/fume/capify/templates/config/deploy.rb",
     "generators/fume/fume_generator.rb",
     "generators/fume/simple_theme/simple_theme_gen.rb",
     "generators/fume/simple_theme/templates/public/demo.html",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_flat_30_cccccc_40x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_flat_50_5c5c5c_40x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_20_555555_1x400.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_40_0078a3_1x400.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_40_ffc73d_1x400.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_gloss-wave_25_333333_500x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_highlight-soft_80_eeeeee_1x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_inset-soft_25_000000_1x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-bg_inset-soft_30_f58400_1x100.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-icons_222222_256x240.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-icons_4b8e0b_256x240.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-icons_a83300_256x240.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-icons_cccccc_256x240.png",
     "generators/fume/simple_theme/templates/public/images/jquery-ui-1.7.2.ui-darkness/ui-icons_ffffff_256x240.png",
     "generators/fume/simple_theme/templates/public/javascripts/jquery-1.3.2.js",
     "generators/fume/simple_theme/templates/public/javascripts/jquery-ui-1.7.2.js",
     "generators/fume/simple_theme/templates/public/javascripts/jquery-ui-i18n-1.7.2.js",
     "generators/fume/simple_theme/templates/public/javascripts/jquery.corner-2.03.js",
     "generators/fume/simple_theme/templates/public/javascripts/jquery.timepicker-0.2.1.js",
     "generators/fume/simple_theme/templates/public/javascripts/simple-theme-ie-patch.js",
     "generators/fume/simple_theme/templates/public/stylesheets/jquery-ui-1.7.2.ui-darkness.css",
     "generators/fume/simple_theme/templates/public/stylesheets/simple-theme.css",
     "generators/fume/simple_theme/templates/public/stylesheets/simple-theme.less",
     "generators/fume/simple_theme/templates/public/stylesheets/src/base.less",
     "generators/fume/simple_theme/templates/public/stylesheets/src/function.less",
     "generators/fume/simple_theme/templates/public/stylesheets/src/layout.less",
     "generators/fume/simple_theme/templates/public/stylesheets/src/reset.less",
     "generators/fume/simple_theme/templates/public/stylesheets/src/vendor/yui-3.0/base.css",
     "generators/fume/simple_theme/templates/public/stylesheets/src/vendor/yui-3.0/fonts.css",
     "generators/fume/simple_theme/templates/public/stylesheets/src/vendor/yui-3.0/reset.css",
     "init.rb",
     "lib/fume.rb",
     "lib/fume/authlogic.rb",
     "lib/fume/rails_ext.rb",
     "lib/fume/searchlogic.rb",
     "lib/fume/simple_theme.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/sunteya/fume}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{a simple rails scaffold.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<authlogic>, [">= 0"])
    else
      s.add_dependency(%q<authlogic>, [">= 0"])
    end
  else
    s.add_dependency(%q<authlogic>, [">= 0"])
  end
end

