# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{fume}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sunteya"]
  s.date = %q{2009-12-02}
  s.email = %q{Sunteya@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "Rakefile",
     "VERSION.yml",
     "fume.gemspec",
     "generators/fume_simple_theme/USAGE",
     "generators/fume_simple_theme/fume_simple_theme_generator.rb",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_flat_30_cccccc_40x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_flat_50_5c5c5c_40x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_20_555555_1x400.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_40_0078a3_1x400.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_glass_40_ffc73d_1x400.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_gloss-wave_25_333333_500x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_highlight-soft_80_eeeeee_1x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_inset-soft_25_000000_1x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-bg_inset-soft_30_f58400_1x100.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-icons_222222_256x240.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-icons_4b8e0b_256x240.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-icons_a83300_256x240.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-icons_cccccc_256x240.png",
     "generators/fume_simple_theme/templates/images/jquery-ui-1.7.2.ui-darkness/ui-icons_ffffff_256x240.png",
     "generators/fume_simple_theme/templates/javascripts/jquery-1.3.2.min.js",
     "generators/fume_simple_theme/templates/javascripts/jquery-ui-1.7.2.full.min.js",
     "generators/fume_simple_theme/templates/javascripts/jquery-ui-i18n-1.7.2.js",
     "generators/fume_simple_theme/templates/stylesheets/base.less",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/ie.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/buttons/icons/cross.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/buttons/icons/key.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/buttons/icons/tick.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/buttons/readme.txt",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/buttons/screen.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/fancy-type/readme.txt",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/fancy-type/screen.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/doc.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/email.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/external.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/feed.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/im.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/pdf.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/visited.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/icons/xls.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/readme.txt",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/link-icons/screen.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/rtl/readme.txt",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/plugins/rtl/screen.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/print.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/screen.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/forms.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/grid.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/grid.png",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/ie.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/print.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/reset.css",
     "generators/fume_simple_theme/templates/stylesheets/blueprint-0.9.1/src/typography.css",
     "generators/fume_simple_theme/templates/stylesheets/drastic-dark.less",
     "generators/fume_simple_theme/templates/stylesheets/jquery-ui-1.7.2.ui-darkness.css",
     "generators/fume_simple_theme/templates/stylesheets/simple-theme.css",
     "generators/fume_simple_theme/templates/stylesheets/simple-theme.less",
     "init.rb",
     "lib/fume.rb",
     "lib/fume/authlogic.rb",
     "lib/fume/searchlogic.rb",
     "lib/fume/simple_theme.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/sunteya/fume}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{a simple rails scaffold.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<authlogic>, [">= 0"])
    else
      s.add_dependency(%q<authlogic>, [">= 0"])
    end
  else
    s.add_dependency(%q<authlogic>, [">= 0"])
  end
end

